### ISSUE TITLE
Typo in Readme? 

### ISSUE THREAD

**Issue by jcdavison** [paymentwall/paymentwall-ruby#6]
https://github.com/paymentwall/paymentwall-ruby#cart-api

```
Paymentwall::Base::setApiType(Paymentwall_Base::API_CART)
```

should be ?

```
Paymentwall::Base::setApiType(Paymentwall::Base::API_CART)
```

I'll fix the readme if so.

**Comment by kristianladd** [comment]
Hi John.

Thanks, you're indeed right and there's a small typo.

On Mon, Aug 10, 2015 at 8:32 PM, John Davison <notifications@github.com>
wrote:

> https://github.com/paymentwall/paymentwall-ruby#cart-api
>
> Paymentwall::Base::setApiType(Paymentwall_Base::API_CART)
>
> should be ?
>
> Paymentwall::Base::setApiType(Paymentwall::Base::API_CART)
>
> I'll fix the readme if so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paymentwall/paymentwall-ruby/issues/6>.
>



-- 

*IVAN KOVALYOV*
Product Manager - Brick
vanya@paymentwall.com
skype: ivan.kovalyov
gtalk: vanya@paymentwall.com

*Paymentwall Inc.*
www.paymentwall.com
Let's meet! [image: White Nights]
<https://www.paymentwall.com/en/events/white-nights-2015-russia?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh&utm_medium=wn15>
White
Nights Conference
<https://www.paymentwall.com/en/events/white-nights-2015-russia?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh&utm_medium=wn15>
St. Petersburg
[image: E3 2015]
<https://www.paymentwall.com/en/events/chinajoy-2015?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh&utm_medium=e3>
ChinaJoy
2015
<https://www.paymentwall.com/en/events/chinajoy-2015?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh&utm_medium=e3>
Shanghai
[image: Europas awards 2015]
<https://www.paymentwall.com/en/events/gdc-europe-2015?utm_source=email_footer&utm_term=14&utm_campaign=061915-zh>
GDC Europe
<https://www.paymentwall.com/en/events/gdc-europe-2015?utm_source=email_footer&utm_term=293&utm_campaign=050515>
Cologne
<https://www.paymentwall.com/?utm_source=email>

San Francisco - Las Vegas - Amsterdam - Berlin - Istanbul - Kiev - Beijing
- Manila - Hanoi - São Paulo

**Comment by jcdavison** [comment]
https://github.com/paymentwall/paymentwall-ruby/pull/7
